### ISSUE TITLE
multiplayer support ?

### ISSUE THREAD

**Issue by amrmostafa800** [SuperGamerTron/SelfRevive#3]
can support multiplayer ?

**Comment by Odin-G** [comment]
It does not support multiplayer as it is only meant as a way to continue playing after dying in singleplayer.

**Comment by amrmostafa800** [comment]
yes i know i ask if he can edit mod to support multiplayer too or create other mod - i will try create mod for this but i not sure if i can or not

**Comment by amrmostafa800** [comment]
ok i create mod do this
https://github.com/amrmostafa800/SelfReviveMultiplayer

**Comment by SuperGamerTron** [comment]
Looks good. It would be better named something like AutomaticRevive since it waits for the grave timer and revives you automatically. It also keeps reviving you after the game is over without being able to do anything. If that's not intended, you could check if the game is over before reviving or force the game to continue.

**Comment by amrmostafa800** [comment]
> Looks good. It would be better named something like AutomaticRevive since it waits for the grave timer and revives you automatically. It also keeps reviving you after the game is over without being able to do anything. If that's not intended, you could check if the game is over before reviving or force the game to continue.

Yes, it was not intended to revive when the game ended
i will try to fix thanks
+website dont contain anything for update name
sry for bad english

**Comment by amrmostafa800** [comment]
ok i fix bug of reviving after the game is over thanks
